# Generated by Django 3.1.2 on 2021-10-08 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_auto_20211007_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('Client', 'Client'), ('Partner', 'Partner')], max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('Announced', 'Announced'), ('Won', 'Won'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Done', 'Done')], max_length=100, null=True)),
                ('date_announced', models.DateTimeField(null=True)),
                ('date_started', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('collaborators', models.ManyToManyField(to='documents.Collaborator')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=20)),
                ('directory', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('allowed_groups', models.ManyToManyField(to='auth.Group')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.project')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
