# Generated by Django 3.1.2 on 2021-11-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='directory',
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=100)),
                ('path', models.CharField(blank=True, default='', max_length=200)),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.folder')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directory', to='documents.folder'),
        ),
    ]
