version: "3"
services:
  db:
    container_name: postgres_aysysdb
    image: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=aysysdb
      - POSTGRES_USER=aysysdb
      - POSTGRES_PASSWORD=4S1stem
volumes:
  postgres_data:
